
    sequenceDiagram
        participant Channel
        participant BFS as Bot Framework Service
        participant WebServer as Web Server
        Note over WebServer: ASP.NET BotController
        participant Connector
        participant Adapter as AdapterWithErrorHandler
        participant BotFrameworkHttpAdapter
        participant BotFrameworkAdapter
        participant BotAdapter
        participant Middleware
        participant TurnContext
        participant ActivityHandler
        participant Bot

        Note left of Channel: User Message, "Hi"
        Note left of Channel: Id: a8ffb080-1c6f-11ea-a34d-01b0ba674590
        activate Channel
        Channel ->> BFS: HTTP POST
        activate BFS
        Note right of Channel: JSON payload of Activity info

        BFS ->> WebServer: HTTP POST
        activate WebServer
        Note right of BFS: JSON Payload of Activity info

        WebServer ->> Adapter: PostAsync()
        activate Adapter
        rect rgba(0, 0, 255, .1)
            Adapter ->> BotFrameworkHttpAdapter: ProcessAsync()
            activate BotFrameworkHttpAdapter
            BotFrameworkHttpAdapter ->> BotFrameworkAdapter: ProcessAsync()
            activate BotFrameworkAdapter
            BotFrameworkAdapter ->> BotAdapter : ProcessActivityAsync()
            activate BotAdapter
        end
            BotAdapter ->> Middleware: RunPipeline()
            activate Middleware
        Note over Adapter, BotAdapter: Adapter
        loop If uncalled Middleware
            Middleware ->> Middleware: OnTurnAsync()
        end

        Middleware ->> ActivityHandler: OnTurnAsync()
        activate ActivityHandler
        Note over Middleware, Bot: Call Turn Handler of Bot registered in Adapter's .ProcessAysnc() call
        alt is Message
                ActivityHandler ->> Bot: OnMessageAsync()
                activate Bot
            
            else is ConversationUpdate
                ActivityHandler ->> Bot: OnConversationUpdateActivityAsync()
            
            else is MessageReaction
                ActivityHandler ->> Bot: OnMessageReactionActivityAsync()
            
            else is Event
                ActivityHandler ->> Bot: OnEventActivityAsync()
            
            else is Unreognized Activity Type
                ActivityHandler ->> Bot: OnUnrecognizedActivityTypeAsync()
        end

        Note right of Bot: Bot Message "Echo: Hi", Id zg2b7fe0-1c6f-11ea-a34d-01b0ba674590
        Note right of Bot: Id zg2b7fe0-1c6f-11ea-a34d-01b0ba674590
        Bot ->> TurnContext: SendActivityAsync()
        activate TurnContext

        alt no callbacks registered
                TurnContext ->> BotAdapter: SendActivitiesThroughAdapter() calls Adapter.SendActivitiesAsync()
            else if registered Middleware
                TurnContext ->> Middleware: SendActivitiesThroughCallbackPipeline()
        end

        loop If uncalled Middleware
            Middleware ->> Middleware: Call next callback in Send Activities List in TurnContext
        end

        Middleware ->> BotAdapter: SendActivitiesThroughAdapter(): 
        BotAdapter ->> BotFrameworkAdapter: SendActivitiesAsync()
        alt has ReplyToId
            BotFrameworkAdapter ->> Connector: ReplyToActivityAsync() 
            activate Connector
        else no ReplyToId
            BotFrameworkAdapter ->> Connector: SendToConversationAsync()
        end

        Connector ->> BFS: ReplyToActivityWithHttpMessagesAsync()

        BFS ->> Channel: HTTP POST

        Channel -->> Bot: 200 OK, Id zg2b7fe0-1c6f-11ea-a34d-01b0ba674590
        Bot -->> Channel: 200 OK, Id a8ffb080-1c6f-11ea-a34d-01b0ba674590

        deactivate TurnContext
        deactivate Bot
        deactivate ActivityHandler
        deactivate Middleware
        deactivate BotAdapter
        deactivate BotFrameworkAdapter
        deactivate BotFrameworkHttpAdapter
        deactivate Adapter
        deactivate WebServer
        deactivate Connector
        deactivate BFS
        deactivate Channel
   